name: GUIPlugin
main: io.github.davidg95.guiplugin.GUIPlugin
version: 0.1
commands:
   gui:
       description: This command will open the GUI.
       usage: /<command>
       permission: GUIPlugin.gui
       permission-message: You don't have <permission>
   rendermap:
       description: This command will re-render the 3D map..
       usage: /<command>
       permission: GUIPlugin.gui
       permission-message: You don't have <permission>