/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.davidg95.guiplugin;

import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import javax.swing.JDialog;
import static javax.swing.JOptionPane.getRootFrame;
import org.bukkit.Bukkit;

/**
 *
 * @author David
 */
public class InfoDialog extends javax.swing.JDialog {

    private static JDialog dialog;

    /**
     * Creates new form InfoDialog
     *
     * @param parent the parent component;
     */
    public InfoDialog(Window parent) {
        super(parent);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setModal(true);
        loadInfo();
    }

    public static void showInfoDialog(Component parent) {
        Window window;
        if (parent instanceof Frame || parent instanceof Dialog) {
            window = (Window) parent;
        } else {
            window = getRootFrame();
        }
        dialog = new InfoDialog(window);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.setVisible(true);
    }

    private void loadInfo() {
        txtVersion.setText(Bukkit.getBukkitVersion());
        txtSpigotVersion.setText(Bukkit.getVersion());
        txtName.setText(Bukkit.getServerName());
        txtProcessor.setText(Runtime.getRuntime().availableProcessors() + "");
        txtAuthentication.setText(Bukkit.getOnlineMode() ? "ENABLED" : "DISABLED");
        txtSpawn.setText(Bukkit.getSpawnRadius() + "");
        txtNether.setText(Bukkit.getAllowNether() ? "ENABLED" : "DISABLED");
        txtEnd.setText(Bukkit.getAllowEnd() ? "ENABLED" : "DISABLED");
        txtMOTD.setText(Bukkit.getMotd());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProcessor = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        lblAuthentication = new javax.swing.JLabel();
        lblSpawnRadius = new javax.swing.JLabel();
        lblNether = new javax.swing.JLabel();
        lblEnd = new javax.swing.JLabel();
        txtVersion = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtProcessor = new javax.swing.JTextField();
        txtAuthentication = new javax.swing.JTextField();
        txtSpawn = new javax.swing.JTextField();
        txtNether = new javax.swing.JTextField();
        txtEnd = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();
        lblMOTD = new javax.swing.JLabel();
        txtMOTD = new javax.swing.JTextField();
        txtSpigotVersion = new javax.swing.JTextField();
        lblSpigotVersion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Server Info");
        setMaximumSize(new java.awt.Dimension(354, 328));
        setMinimumSize(new java.awt.Dimension(354, 328));
        setResizable(false);

        lblProcessor.setText("Processor Cores:");

        lblName.setText("World Name:");

        lblVersion.setText("Server Version");

        lblAuthentication.setText("Authentication");

        lblSpawnRadius.setText("Spawn Radius:");

        lblNether.setText("Nether:");

        lblEnd.setText("End:");

        btnClose.setText("Close");
        btnClose.setMaximumSize(new java.awt.Dimension(80, 80));
        btnClose.setMinimumSize(new java.awt.Dimension(80, 80));
        btnClose.setPreferredSize(new java.awt.Dimension(80, 80));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblMOTD.setText("MOTD:");

        lblSpigotVersion.setText("Spigot Version:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMOTD)
                    .addComponent(lblEnd)
                    .addComponent(lblNether)
                    .addComponent(lblSpawnRadius)
                    .addComponent(lblAuthentication)
                    .addComponent(lblVersion)
                    .addComponent(lblName)
                    .addComponent(lblProcessor)
                    .addComponent(lblSpigotVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSpigotVersion)
                    .addComponent(txtAuthentication)
                    .addComponent(txtSpawn)
                    .addComponent(txtNether)
                    .addComponent(txtEnd)
                    .addComponent(txtVersion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProcessor)
                    .addComponent(txtMOTD))
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVersion)
                    .addComponent(txtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSpigotVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpigotVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProcessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProcessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthentication)
                    .addComponent(txtAuthentication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpawnRadius)
                    .addComponent(txtSpawn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNether)
                    .addComponent(txtNether, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnd)
                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMOTD)
                    .addComponent(txtMOTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblAuthentication;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblMOTD;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNether;
    private javax.swing.JLabel lblProcessor;
    private javax.swing.JLabel lblSpawnRadius;
    private javax.swing.JLabel lblSpigotVersion;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JTextField txtAuthentication;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtMOTD;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNether;
    private javax.swing.JTextField txtProcessor;
    private javax.swing.JTextField txtSpawn;
    private javax.swing.JTextField txtSpigotVersion;
    private javax.swing.JTextField txtVersion;
    // End of variables declaration//GEN-END:variables
}
